### ISSUE TITLE
Create organisation not possible

### ISSUE THREAD

**Issue by 5-mark** [gamedaoco/gamedao-haiku#448]
**Describe the bug**
When trying to create an organisation and providing logo & header I cannot click the Save on Chain button as its inactive.

**To Reproduce**
1. Start create organisation process
2. select all default values
3. upload logo & header
4. See save on chain button not active or screenshots or conole log 

**Expected behavior**
It should be possible to create an organisation 

**Screenshots**
![image](https://user-images.githubusercontent.com/91988132/194559577-9cd40031-6023-4a83-bdc6-969721e7869d.png)

**Additional context**

```
TRACE useCreateOrgTransaction: Error: Cannot convert 'Token' via asForeignAsset
    at _app-dfea0a64e3f1f46b.js:101:590359
    at _app-dfea0a64e3f1f46b.js:101:575886
    at r.get [as asForeignAsset] (_app-dfea0a64e3f1f46b.js:101:575819)
    at t.exports (511-bbb99145433caeec.js:1:15608)
    at t.exports (511-bbb99145433caeec.js:1:23853)
    at xt._cast (511-bbb99145433caeec.js:1:54891)
    at xt.cast (511-bbb99145433caeec.js:1:41279)
    at xt._cast (511-bbb99145433caeec.js:1:55132)
    at xt._validate (511-bbb99145433caeec.js:1:41832)
    at xt._validate (511-bbb99145433caeec.js:1:55439)
(anonymous) @ _app-dfea0a64e3f1f46b.js:101
(anonymous) @ [...param]-8bdcae33ea91e228.js:1
ri @ framework-49f1e091cbf6b261.js:1
Ss @ framework-49f1e091cbf6b261.js:1
is @ framework-49f1e091cbf6b261.js:1
jl @ framework-49f1e091cbf6b261.js:1
(anonymous) @ framework-49f1e091cbf6b261.js:1
ws @ framework-49f1e091cbf6b261.js:1
ls @ framework-49f1e091cbf6b261.js:1
S @ framework-49f1e091cbf6b261.js:1
T @ framework-49f1e091cbf6b261.js:1
```

**Comment by DarkNebula0** [comment]
Has already been fixed in dev branch. Can you test on. https://dev.gamedao.co/
